### PR TITLE
Disable OSGI dependencies

### PR DESCRIPTION
**Pull request by rtimush**
* Do not repack JAR files because it is slow and unnecessary
 * Do not add osgi dependencies to RPMs

### CODE REVIEW

**Comment by dornatsky** [comment]
what does it do?

**Comment by rtimush** [comment]
@dornatsky added description

**Comment by dornatsky** [comment]
what are these osgi dependencies and why we don't need them?

**Comment by rtimush** [comment]
https://fedoraproject.org/wiki/Features/OSGiAutoDeps
One more "clever" idea from RPM authors that works if you distribute JARs as individual RPMs, but breaks self-contained java applications' packaging.
We don't need to depend on external OSGI bundles because we bring all our dependencies with us (and actually do not use OSGI).

**Comment by dornatsky** [comment]
okay

**Pull request merged**
